### ISSUE TITLE
Not able to open project in UE5

### ISSUE THREAD

**Issue by adityaVR** [readyplayerme/UE5-WebView-Example#1]
Hi Team

I am getting below error when I am trying to open WebView project in UE5

[Issue](https://ibb.co/4swb7wx)

if I go ahead and click yes then it says -
WebView_UE5 could not be compiled. Try rebuilding from source manually.

Kindly guide.

**Comment by HarrisonHough** [comment]
If you right-click the `WebView_UE5.uproject` file, click "Generate visual studio files", then open the `WebView_UE5.sln` and try to build from Visual Studio (or another IDE) do you get any errors?

**Comment by adityaVR** [comment]
@HarrisonHough  When i follow step suggested by you , I get below error=
ERROR: UnrealBuildTool requires at minimum the MSVC 14.29.30133 toolchain. Please install a later toolchain from the Visual Studio installer.

**Comment by adityaVR** [comment]
@HarrisonHough  I am able to open project after updating Visual studio from Visual studio installer. Thank you :)

**Comment by HarrisonHough** [comment]
> @HarrisonHough I am able to open project after updating Visual studio from Visual studio installer. Thank you :) but now I am facing other issue : Failed to load map! Umap appears to be an asset file . I checked project setting >> map & modes >> editor startup map. Nothing is set here. neither I am able set any default map here.

Did you download the Project as a Zip from Git or did you clone the repository using Github?
Because the git repository uses LFS (Large File System) downloading the project as a Zip will cause issues, so you need to clone the repo instead and this should fix that issue.

**Comment by HarrisonHough** [comment]
You're not the first person to report this issue though so I might consider removing LFS to prevent such issues.

**Comment by HarrisonHough** [comment]
Okay I have updated some repo settings so downloading the project as a zip should work now.

**Comment by adityaVR** [comment]
Yes It worked now. and it was exactly same issue which you mentioned. Thanks for quick help.

**Comment by adityaVR** [comment]
Yes It worked now. and it was exactly same issue which you mentioned. Thanks for quick help.
